# Numpy Basics

En el presente archivo se propone como objetivos principales los mencionados: 
1. Aprendizaje e implementación de NumPy en proyectos. 
2. Aprendizaje y práctica en el manejo de Jupyter Notebook

El código utilizado y el tutorial a seguir se encuentran en la <a href="https://numpy.org/doc/stable/user/absolute_beginners.html">página oficial de NumPy</a>.

## Creación de arrays

In [22]:
def d(array):
    print(array)

In [23]:
import numpy as np    # np es una convención utilizada y aceptada para mayor legibilidad

# np.array()
a = np.array([1,2,3,4,5])

# np.arange(inicio, final, paso)
b = np.arange(0, 5, 1)

# la dimensión de un array es denominado axes en NumPy

# np.linspace(inicio, final, cantidad de numeros en el medio)
c = np.linspace(1, 11, 5)

# np.zeros(cantidad de ceros en array)
e = np.zeros(2)

# np.ones(cantidad de unos)
f = np.ones(3)

# np.empty(size) array con numeros random
g = np.empty(9)

# Imprimir resultados
d(a)
d(b)
d(c)
d(e)
d(f)
d(g)

[1 2 3 4 5]
[0 1 2 3 4]
[ 1.   3.5  6.   8.5 11. ]
[0. 0.]
[1. 1. 1.]
[6.23042070e-307 4.67296746e-307 1.69121096e-306 3.33772113e-307
 2.67018234e-306 1.42413555e-306 1.78019082e-306 1.37959740e-306
 2.29178686e-312]


## Operaciones: concatenación, remover y ordenamiento

In [ ]:
# np.sort()
