# Numpy Basics

En el presente archivo se propone como objetivos principales los mencionados: 
1. Aprendizaje e implementación de NumPy en proyectos. 
2. Aprendizaje y práctica en el manejo de Jupyter Notebook

El código utilizado y el tutorial a seguir se encuentran en la <a href="https://numpy.org/doc/stable/user/absolute_beginners.html">página oficial de NumPy</a>.

## Creación de arrays

In [2]:
def d(array):
    print(array)

In [3]:
import numpy as np    # np es una convención utilizada y aceptada para mayor legibilidad

# np.array()
a = np.array([1,2,3,4,5])

# np.arange(inicio, final, paso)
b = np.arange(0, 5, 1)

# la dimensión de un array es denominado axes en NumPy

# np.linspace(inicio, final, cantidad de numeros en el medio)
c = np.linspace(1, 11, 5)

# np.zeros(cantidad de ceros en array)
e = np.zeros(2)

# np.ones(cantidad de unos)
f = np.ones(3)

# np.empty(size) array con numeros random
g = np.empty(9)

# Imprimir resultados
d(a)
d(b)
d(c)
d(e)
d(f)
d(g)

[1 2 3 4 5]
[0 1 2 3 4]
[ 1.   3.5  6.   8.5 11. ]
[0. 0.]
[1. 1. 1.]
[0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 7.35169681e-321 1.06166640e-153 2.59345405e+161
 2.46089539e-154]


## Operaciones: concatenación, remover y ordenamiento

In [13]:
# np.sort(array)
a = np.array([4,5,6,3,2,1,9,0,7,8])
b = np.sort(b)
d(a)
d(b)

# np.concatenate((arr1, arr2))
c = np.concatenate((a, b), axis=0) # 1 dimension array, axis=1
d(c)

# la utilizacion de esta ultima se pasan los arrays dentro de una tupla

[4 5 6 3 2 1 9 0 7 8]
[0 1 2 3 4]
[4 5 6 3 2 1 9 0 7 8 0 1 2 3 4]


## Forma, dimensión y tamaño de un array

In [46]:
# array.ndim    devuelve axes, o la dimensión del array 
# array.size    devuelve el tamaño del array que es el producto del array.shape, 
#               como es fila x columna entonces es lo mismo que la cantidad de elementos en array
# array.shape   devuelve el tamaño del array en una tupla: (row, column, elements)

#      (column)  (column)
# (row) ---+---|----+-----
# (row) ---+---|----+-----


array = np.array([[1,2,3],
                  [4,5,6]])
d(array)
d(array.ndim)
d(array.size)
d(array.shape)

# array.reshape(row, column) devuelve copia del original cambiando la dimensión
new_array = array.reshape(1,6)
print('new array: ')
d(new_array)

# np.reshape(array, newshape=(row, column), order='')
new_array = np.reshape(new_array, newshape=(3,2))
print('3x2 array: ', end='')
d(new_array)

# Nota: al usar reshape es necesario tener en cuenta la cantidad de elementos: 
# array final debe tener la misma cantidad de elementos que array original.

[[1 2 3]
 [4 5 6]]
2
6
(2, 3)
new array: 
[[1 2 3 4 5 6]]
3x2 array: [[1 2]
 [3 4]
 [5 6]]


## Conversión 1D a 2D

In [47]:
# saltear
# np.newaxis
# np.expand_dims 

## Indexing & Slicing

In [9]:
# Utilización igual que en listas de python:  array[inicio:final] -> array[(incluye:(no incluye)]
import numpy as np

arr = np.array([1,2,3,4,5,6])
print(arr[:-3])   # [1,2,3]


# slicing con condiciones: devuelve un array con los elementos que cumplen con la condición
arr = np.array([[1 , 2, 3, 4], 
                [5, 6, 7, 8], 
                [9, 10, 11, 12]])

print(arr[arr > 10])         # [11, 12]

even_number = arr[arr%2==0]  # select even number from array
print(even_number)


# intersección & y |
interseccion = arr[(arr > 5) & (arr%2==0)]  # numeros en array mayor a cinco y multiplos de dos
print(interseccion)


[1 2 3]
[11 12]
[ 2  4  6  8 10 12]
[ 6  8 10 12]


## Array creation from existing data (array)

In [ ]:
# usando slicing y creando nuevo array a base de copia de original
a = np.arange(1, 21, 1)
copy_a = a[3:8]               # [4,5,6,7,8]
print(copy_a[copy_a%2==0])    # solo los numeros pares
print()

# np.vstack((arr1, arr2))   es como el concatenar pero en vertical
a1 = np.arange(4).reshape(2,2)
#  [[0 1]
#  [2 3]]

a2 = np.arange(5,9).reshape(2,2)
#  [[5 6]
#  [7 8]]

b = np.vstack((a1, a2))
print(b)
print()


# np.hstack((arr1, arr2))   es como el concatenar pero en horizontal: deben tener la misma dimensión
c = np.hstack((a1, a2))
print(c)
print()


# np.hsplit(array, cantidad de split) el split realizado respeta la dimensión del array original
arr = np.arange(1,19).reshape(3,6)
print(arr)
# [[ 1  2  3  4  5  6]
#  [ 7  8  9 10 11 12]
#  [13 14 15 16 17 18]]

split_arr = np.hsplit(arr, 3)
print(split_arr)

# np.vsplit(array, (forma))              este corta verticalmente, y por ende si es un array de 2x3 y lo dividís por 2,
                                       # entonces van a ser 2 array de 3 elementos
split_arr = np.vsplit(arr, 3)
print(split_arr)


## Operaciones básicas con arrays