# Numpy Basics

En el presente archivo se propone como objetivos principales los mencionados: 
1. Aprendizaje e implementación de NumPy en proyectos. 
2. Aprendizaje y práctica en el manejo de Jupyter Notebook

El código utilizado y el tutorial a seguir se encuentran en la <a href="https://numpy.org/doc/stable/user/absolute_beginners.html">página oficial de NumPy</a>.

## Creación de arrays

In [2]:
def d(array):
    print(array)

In [3]:
import numpy as np    # np es una convención utilizada y aceptada para mayor legibilidad

# np.array()
a = np.array([1,2,3,4,5])

# np.arange(inicio, final, paso)
b = np.arange(0, 5, 1)

# la dimensión de un array es denominado axes en NumPy

# np.linspace(inicio, final, cantidad de numeros en el medio)
c = np.linspace(1, 11, 5)

# np.zeros(cantidad de ceros en array)
e = np.zeros(2)

# np.ones(cantidad de unos)
f = np.ones(3)

# np.empty(size) array con numeros random
g = np.empty(9)

# Imprimir resultados
d(a)
d(b)
d(c)
d(e)
d(f)
d(g)

[1 2 3 4 5]
[0 1 2 3 4]
[ 1.   3.5  6.   8.5 11. ]
[0. 0.]
[1. 1. 1.]
[0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 7.35169681e-321 1.06166640e-153 2.59345405e+161
 2.46089539e-154]


## Operaciones: concatenación, remover y ordenamiento

In [13]:
# np.sort(array)
a = np.array([4,5,6,3,2,1,9,0,7,8])
b = np.sort(b)
d(a)
d(b)

# np.concatenate((arr1, arr2))
c = np.concatenate((a, b), axis=0) # 1 dimension array, axis=1
d(c)

# la utilizacion de esta ultima se pasan los arrays dentro de una tupla

[4 5 6 3 2 1 9 0 7 8]
[0 1 2 3 4]
[4 5 6 3 2 1 9 0 7 8 0 1 2 3 4]


## Forma, dimensión y tamaño de un array

In [46]:
# array.ndim    devuelve axes, o la dimensión del array 
# array.size    devuelve el tamaño del array que es el producto del array.shape, 
#               como es fila x columna entonces es lo mismo que la cantidad de elementos en array
# array.shape   devuelve el tamaño del array en una tupla: (row, column, elements)

#      (column)  (column)
# (row) ---+---|----+-----
# (row) ---+---|----+-----


array = np.array([[1,2,3],
                  [4,5,6]])
d(array)
d(array.ndim)
d(array.size)
d(array.shape)

# array.reshape(row, column) devuelve copia del original cambiando la dimensión
new_array = array.reshape(1,6)
print('new array: ')
d(new_array)

# np.reshape(array, newshape=(row, column), order='')
new_array = np.reshape(new_array, newshape=(3,2))
print('3x2 array: ', end='')
d(new_array)

# Nota: al usar reshape es necesario tener en cuenta la cantidad de elementos: 
# array final debe tener la misma cantidad de elementos que array original.

[[1 2 3]
 [4 5 6]]
2
6
(2, 3)
new array: 
[[1 2 3 4 5 6]]
3x2 array: [[1 2]
 [3 4]
 [5 6]]


## Conversión 1D a 2D

In [47]:
# saltear
# np.newaxis
# np.expand_dims 

## Indexing & Slicing

In [ ]:
# Utilización igual que en listas de python:  array[inicio:final] -> array[(incluye:(no incluye)]
