# Numpy Basics

En el presente archivo se propone como objetivos principales los mencionados: 
1. Aprendizaje e implementación de NumPy en proyectos. 
2. Aprendizaje y práctica en el manejo de Jupyter Notebook

El código utilizado y el tutorial a seguir se encuentran en la <a href="https://numpy.org/doc/stable/user/absolute_beginners.html">página oficial de NumPy</a>.

## Creación de arrays

In [1]:
import pprint
def display(message, array):
    print(f'{message}: ')
    pprint.pprint(array)
    print('----------------------------')

In [28]:
import numpy as np    # np es una convención utilizada y aceptada para mayor legibilidad

# np.array()
a = np.array([1,2,3,4,5])

# np.arange(inicio, final, paso)
b = np.arange(0, 5, 1)

# la dimensión de un array es denominado axes en NumPy

# np.linspace(inicio, final, cantidad de numeros en el medio)
c = np.linspace(1, 11, 5)

# np.zeros(cantidad de ceros en array)
# np.zeros((shape)) ex. np.zeros((4, 5))
e = np.zeros(2)

# np.ones(cantidad de unos)
# np.ones((shape)) ex. np.ones((2, 3))
f = np.ones(3)

# np.empty(size) array con numeros random
g = np.empty(9)

# Imprimir resultados
display('a', a)
display('b', b)
display('c', c)
display('e', e)
display('f', f)
display('g', g)

a: 
array([1, 2, 3, 4, 5])
----------------------------

b: 
array([0, 1, 2, 3, 4])
----------------------------

c: 
array([ 1. ,  3.5,  6. ,  8.5, 11. ])
----------------------------

e: 
array([0., 0.])
----------------------------

f: 
array([1., 1., 1.])
----------------------------

g: 
array([4.24399158e-314, 8.48798317e-314, 1.27319747e-313, 1.69759663e-313,
       2.12199579e-313, 2.54639495e-313, 2.97079411e-313, 3.39519327e-313,
       3.81959242e-313])
----------------------------



## Operaciones: concatenación, remover y ordenamiento

In [13]:
# np.sort(array)
a = np.array([4,5,6,3,2,1,9,0,7,8])
b = np.sort(b)
d(a)
d(b)

# np.concatenate((arr1, arr2))
c = np.concatenate((a, b), axis=0) # 1 dimension array, axis=1
d(c)

# la utilizacion de esta ultima se pasan los arrays dentro de una tupla

[4 5 6 3 2 1 9 0 7 8]
[0 1 2 3 4]
[4 5 6 3 2 1 9 0 7 8 0 1 2 3 4]


## Forma, dimensión y tamaño de un array

In [46]:
# array.ndim    devuelve axes, o la dimensión del array 
# array.size    devuelve el tamaño del array que es el producto del array.shape, 
#               como es fila x columna entonces es lo mismo que la cantidad de elementos en array
# array.shape   devuelve el tamaño del array en una tupla: (row, column, elements)

#      (column)  (column)
# (row) ---+---|----+-----
# (row) ---+---|----+-----


array = np.array([[1,2,3],
                  [4,5,6]])
d(array)
d(array.ndim)
d(array.size)
d(array.shape)

# array.reshape(row, column) devuelve copia del original cambiando la dimensión
new_array = array.reshape(1,6)
print('new array: ')
d(new_array)

# np.reshape(array, newshape=(row, column), order='')
new_array = np.reshape(new_array, newshape=(3,2))
print('3x2 array: ', end='')
d(new_array)

# Nota: al usar reshape es necesario tener en cuenta la cantidad de elementos: 
# array final debe tener la misma cantidad de elementos que array original.

[[1 2 3]
 [4 5 6]]
2
6
(2, 3)
new array: 
[[1 2 3 4 5 6]]
3x2 array: [[1 2]
 [3 4]
 [5 6]]


## Conversión 1D a 2D

In [47]:
# saltear
# np.newaxis
# np.expand_dims 

## Indexing & Slicing

In [1]:
# Utilización igual que en listas de python:  array[inicio:final] -> array[(incluye:(no incluye)]
import numpy as np

arr = np.array([1,2,3,4,5,6])
print(arr[:-3])   # [1,2,3]


# slicing con condiciones: devuelve un array con los elementos que cumplen con la condición
arr = np.array([[1 , 2, 3, 4], 
                [5, 6, 7, 8], 
                [9, 10, 11, 12]])

print(arr[arr > 10])         # [11, 12]

even_number = arr[arr%2==0]  # select even number from array
print(even_number)


# intersección & y |
interseccion = arr[(arr > 5) & (arr%2==0)]  # numeros en array mayor a cinco y multiplos de dos
print(interseccion)


[1 2 3]
[11 12]
[ 2  4  6  8 10 12]
[ 6  8 10 12]


## Array creation from existing data (array)

In [2]:
import numpy as np

# usando slicing y creando nuevo array a base de copia de original
a = np.arange(1, 21, 1)
copy_a = a[3:8]               # [4,5,6,7,8]
print(copy_a[copy_a%2==0])    # solo los numeros pares
print()

# np.vstack((arr1, arr2))   es como el concatenar pero en vertical
a1 = np.arange(4).reshape(2,2)
#  [[0 1]
#  [2 3]]

a2 = np.arange(5,9).reshape(2,2)
#  [[5 6]
#  [7 8]]

b = np.vstack((a1, a2))
print(b)
print()


# np.hstack((arr1, arr2))   es como el concatenar pero en horizontal: deben tener la misma dimensión
c = np.hstack((a1, a2))
print(c)
print()


# np.hsplit(array, cantidad de split) el split realizado respeta la dimensión del array original
arr = np.arange(1,19).reshape(3,6)
print(arr)
# [[ 1  2  3  4  5  6]
#  [ 7  8  9 10 11 12]
#  [13 14 15 16 17 18]]

split_arr = np.hsplit(arr, 3)
print(split_arr)

# np.vsplit(array, (forma))              este corta verticalmente (columna), y por ende si es un array de 2x3 y lo dividís por 2,
                                       # entonces van a ser 2 array de 3 elementos
split_arr = np.vsplit(arr, 3)
print(split_arr)
print()

# array.view() y array.copy()
# En el array.view() se crea una copia del original pero comparten mismo puntero y se modifican el mismo array
# En el array.copy() se crea una copia del original pero son dos arrays distintos

a = np.arange(21).reshape(3,7)
print(a)
b = a.view()
b[0][0] = 97
print(a)

# array.copy()
b = a.copy()
b[0][0] = 76
print(b)
print(a)

[4 6 8]

[[0 1]
 [2 3]
 [5 6]
 [7 8]]

[[0 1 5 6]
 [2 3 7 8]]

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
[array([[ 1,  2],
       [ 7,  8],
       [13, 14]]), array([[ 3,  4],
       [ 9, 10],
       [15, 16]]), array([[ 5,  6],
       [11, 12],
       [17, 18]])]
[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18]])]

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]
[[97  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]
[[76  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]
[[97  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]


## Operaciones básicas con arrays

In [27]:
# sumas, restas, multiplicación y división 
import pprint
a = np.arange(41, 45).reshape(2, 2)
b = np.arange(1, 5).reshape(2, 2)
display('a', a)
display('b', b)
display('a + b', a+b)
display('a - b', a-b)

# multiplicación y división es distinta al producto de matrices; en este caso se da entre celdas y celdas
display('a * b', a*b)
# teniendo dos 'matrices' a=[[41, 42], [43, 44]] y b=[[1, 2], [3, 4]], 
# el producto de estas deberia ser a.b=[[167, 250], [175, 262]]
display('a / b', a/b)


# array.sum()  -> calcula la suma total de los elementos que pertenecen al array
my_array = np.arange(1, 11).reshape(5, 2)
print(f'my_array.sum(): {my_array.sum()}')
my_array = my_array.reshape(2, 5)
display('my_arra.sum()', my_array.sum())


# broadcasting -> multiplicación de escalar x vector -> se realiza la multiplicación del escalar por cada celda
display('b * 1.8', b*1.8)


# array.max()
my_arr = np.arange(1, 11)
print("my_arr = ", my_arr)
display('my_arr.max()', my_arr.max())

# array.min()
display('my_arr.min()', my_arr.min())

# array.mean() --> average 
display('my_arr.mean()', my_arr.mean())

# array.prod() --> multiplication of elements in array
display('my_arr.prod()', my_arr.prod())

# array.std() --> standard deviation
display('my_arr.std()', my_arr.std())


# np.unique() --> elementos únicos 
c = np.array([x for x in range(15) if x % 2 == 0])
print(c)

SyntaxError: invalid syntax (3906135117.py, line 47)

## 2-D array (matrix)

In [18]:
# axis=0 --> columns 
# axis=1 --> rows

import numpy as np 

matrix = np.arange(1, 13).reshape(3, 4)
display('matrix', matrix)

# array.min(axis)
matrix.sum(axis=1)

# indexing
print('matrix[0][1]: ', matrix[0][1])
display('matrix[0, 1]', matrix[0, 1])

# slicing mtrx[row:row, column:column] 
# seleccion de 6, 7, 10, 11
display('matrix[1:3, 1:3]', matrix[1:3, 1:3])


# transponer matriz --> 


matrix: 
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])
----------------------------
matrix[0][1]:  2
matrix[0, 1]: 
2
----------------------------
matrix[1:3, 1:3]: 
array([[ 6,  7],
       [10, 11]])
----------------------------


### Random number generation

In [23]:
import numpy as np

# random.Generator class
rng = np.random.default_rng()

# generator.integers(stop, size=(row, column))
new_array = rng.integers(6, size=(3, 2))
display('new_array (random)', new_array)

new_array (random): 
array([[1, 5],
       [4, 4],
       [1, 2]], dtype=int64)
----------------------------
